[project]
name = "scrapers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "fire>=0.7.1",
    "playwright>=1.40.0",
    "requests>=2.32.5",
    "pyyaml>=6.0.2",
    "redgifs>=2.3.0",
]
